### ISSUE TITLE
ValueError: could not broadcast input array from shape (1382368) into shape (11058944)

### ISSUE THREAD

**Issue by dashsiddharth** [holgern/pyedflib#41] opened 2018-09-07 07:44 UTC
runs the code as per documentation and got a value error 
```Python
import pyedflib
import numpy as np
f = pyedflib.EdfReader("data/flow/mesa-sleep-0001.edf")
n = f.signals_in_file
signal_labels = f.getSignalLabels()
sigbufs = np.zeros((n, f.getNSamples()[0]))
for i in np.arange(n):
    sigbufs[i, :] = f.readSignal(i)
```

**Comment by skjerns** [comment] 2020-02-29 13:04
Duplicate of #32 solved there.

If the sampling frequency of your signals are different, you need to load the sigbufs into a list instead of a numpy array

**Closed by skjerns** 2020-02-29 13:04 UTC
